### ISSUE TITLE
Confidential mode

### ISSUE THREAD

**Issue by jamesmalin** [jeremyephron/simplegmail#27]
Hi Jeremy,

Hope everything is going well over there. I haven't looked into this yet, but thought this would a great feature to add. Not sure if you have ever used this before yourself.

Sometimes you send an email that you do not want to be forwarded to another recipient. Examples could be a paid for service that attaches a CSV or Excel spreadsheet, email that you want only the one recipient to have access to, other confidential type of information, etc.

Can you look into this?
https://www.makeuseof.com/tag/prevent-emails-forwarded-outlook-gmail/

**Comment by jamesmalin** [comment]
Specific reference:
https://developers.google.com/contacts/v3/reference#gcSensitivity

**Comment by jeremyephron** [comment]
@jamesmalin A brief google search and scan through the Gmail API endpoints seems to show that this is not possible through the API, and can only be done through the Gmail client

**Comment by jamesmalin** [comment]
Okay. I found a reference in the python Gmail client module under MISC for the people v1 API. Didn't dig or search more than that.
