### ISSUE TITLE
retrieving raw headers from gmail API

### ISSUE THREAD

**Issue by rosstex** [jeremyephron/simplegmail#39]
Actually just one Q, I don't see that `message.py` has a way to access the raw email headers. Is that something that Google's API provides? (For example, I would like to view DKIM signatures and [Feedback IDs](https://support.google.com/mail/answer/6254652).)

**Comment by jeremyephron** [comment]
I currently don't grab those, but I can look into adding that functionality soon.

**Comment by jeremyephron** [comment]
@rosstex v4.0.1 exposes the message headers automatically as a dict from header name to value `Message.headers`.

```
msgs = gmail.get_messages(...)
msg = msgs[0]

dkim_sig = msg.headers['DKIM-Signature']
feedback_id = msg.headers['Feedback-ID']
```

No particular headers are guaranteed to exist, so make sure to check for the key's existence first, and you can see what keys are available for a given message with `msg.headers.keys()`.

**Comment by rosstex** [comment]
Awesome, thank you!!
