### ISSUE TITLE
Case insensitive email headers

### ISSUE THREAD

**Issue by rosstex** [jeremyephron/simplegmail#42]
I noticed something funky with an email that contained a lowercase 'from' header. Turns out, email headers can be case insensitive: https://stackoverflow.com/a/6143644/3385741

The parsing of 'sender' and 'recipient' currently do not account for this.

**Comment by jeremyephron** [comment]
@rosstex Thanks for figuring that out! It has been fixed in ce8dc03 and released in v4.0.3.
