### ISSUE TITLE
Custom folder for credential file

### ISSUE THREAD

**Issue by sicenul** [jeremyephron/simplegmail#43]
Is it possible to set custom folder for credential files? (client_secret.json and gmail_token.json)
I'd like to save and read it not from root directory of application, but from other sub folder
Please show me how if possible. Thanks.

**Comment by jeremyephron** [comment]
@sicenul Yes, it is possible, with the `client_secret_file` and `creds_file` parameters of the `Gmail` object.

When you create the object just pass in the desired paths, e.g., 

```python3
gmail = Gmail(client_secret_file='/path/to/secret.json', creds_file='/path/to/store/creds.json')
```
