### ISSUE TITLE
any old version compatible with Python 3.4 ?

### ISSUE THREAD

**Issue by abubelinha** [jeremyephron/simplegmail#45]
I would like to try this package in an old WinXP 32bit computer.
The newest Python version I can use there is 3.4.4, and it seems lxml highest compatible version is 4.3.1

So this fails:
```Python
C:\>c:\python34\scripts\pip install simplegmail
Collecting simplegmail
  Downloading https://files.pythonhosted.org/packages/3e/43/8a50f4d4c300a778fdebe95dc194a83d38d1bdac4ebb036c85f4e0d39b02/simplegmail-4.0.3-py3-none-any.whl
Collecting lxml>=4.4.2 (from simplegmail)
  ERROR: Could not find a version that satisfies the requirement lxml>=4.4.2 (from simplegmail) (from versions: 0.9, ... 4.4.0)
ERROR: No matching distribution found for lxml>=4.4.2 (from simplegmail)

C:\>c:\python34\scripts\pip install lxml
Requirement already satisfied: lxml in c:\python34\lib\site-packages (4.3.1)
```

Is there any way to install an old (unsupported) simplegmail version which does not require lxml beyond 4.3.1?

Thanks a lot

**Comment by jeremyephron** [comment]
@abubelinha I'm sorry to say that the package does not support python versions earlier than 3.6 (this is sensible since not even Microsoft supports XP anymore). If you have programming experience you can try to remove all the 3.6 features, until it runs on 3.4, but that's about it.
