### ISSUE TITLE
attachment.save() fails if the file already exists

### ISSUE THREAD

**Issue by rasa** [jeremyephron/simplegmail#67]
The `overwrite` check here should be `not overwrite`:

https://github.com/jeremyephron/simplegmail/blob/e48164525b4573b63f0ef9bbb467c5cee0afa348/simplegmail/attachment.py#L100-L105

**Comment by rob-smallshire** [comment]
Looks like a duplicate of #56

**Comment by rasa** [comment]
> Looks like a duplicate of #56

@rob-smallshire Correct. Closing.
