### ISSUE TITLE
Is plain text deprecated on Gmail service?

### ISSUE THREAD

**Issue by gexzam** [jeremyephron/simplegmail#83]
Hi jeremy... I love your library
If i call `message.plain` output is None.
Nevertheless if i send an plain text email to myself, `message.plain` works fine.
Is there a possibility that Gmail is hiding plain text part of a message and delivering HTML version only?
Thanks.

**Comment by duyanh3101** [comment]
same problem, is there any solution?

**Comment by sneakerush** [comment]
Was this ever solved?

**Comment by jeremyephron** [comment]
Plaintext is not deprecated but not every email client will set a plaintext message. The Gmail web client (mail.google.com), for example, will correctly set a plaintext message. If message.plain is None, you should parse the html field in your application. Let me know if there are more details to this issue, but as far as I can tell this is not specific to the API or library.
